#!/usr/bin/env bash

set -eu

if ! cargo +nightly fmt --all -- --check; then
  echo "There are some code style issues."
  echo "Run cargo fmt first."
  exit 1
fi

if ! cargo clippy --all-targets --all-features --tests -- -D warnings; then
  echo "There are some clippy issues."
  exit 1
fi

if ! cargo nextest run -j num-cpus --all-features; then
  echo "There are some test issues."
  exit 1
fi

if ! cargo test --doc --all-features; then
  echo "There are some doc test issues."
  exit 1
fi

exit 0
